# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: tlowac
          template: classic
          base: activity, community, repositories
          base_hireable: yes
          config_display: large
          config_padding: 1, 8 + 10%
          config_timezone: Asia/Seoul

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 298
          plugin_activity_visibility: all
          
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.rss.svg
          token: NOT_NEEDED
          base: ""
          plugin_rss: yes
          plugin_rss_limit: 2
          plugin_rss_source: https://helicopter55.tistory.com/rss
